# Generated by Django 2.0.2 on 2018-02-25 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baggage_Content_Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CONTENT_ID', models.IntegerField()),
                ('CONTENT_IMG', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Baggage_Desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BAG_ID', models.IntegerField()),
                ('WAREHOUSE_BAG_ID', models.IntegerField()),
                ('BAG_COLOR', models.CharField(max_length=10)),
                ('BAG_SIZE', models.IntegerField()),
                ('BAG_BRAND', models.CharField(max_length=20)),
                ('KEY_IDENTIF_ITEM', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Baggage_Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMG_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNF_NUM', models.IntegerField()),
                ('MILEAGEPLS_NUM', models.IntegerField()),
                ('FIRST_NAME', models.CharField(max_length=30)),
                ('LAST_NAME', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REPO_ID', models.IntegerField()),
                ('REPO_STAT', models.CharField(max_length=10)),
                ('CUST_EMAIL', models.CharField(max_length=20)),
                ('CUST_PHONE', models.IntegerField()),
                ('CUST_PERM_ADDR', models.CharField(max_length=50)),
                ('CUST_TEMP_ADDR', models.CharField(max_length=50)),
                ('BAG_DESC_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='File_missing_report.Baggage_Desc')),
                ('REPO_CNF_NUM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conf_num', to='File_missing_report.Customer')),
                ('REPO_MILEAGEPLS_NUM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_num', to='File_missing_report.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='baggage_img',
            name='IMG_CNF_NUM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag_img_conf_num', to='File_missing_report.Customer'),
        ),
        migrations.AddField(
            model_name='baggage_img',
            name='IMG_MILEAGEPLS_NUM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag_img_mileage_num', to='File_missing_report.Customer'),
        ),
        migrations.AddField(
            model_name='baggage_desc',
            name='BAG_CNF_NUM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag_conf_num', to='File_missing_report.Customer'),
        ),
        migrations.AddField(
            model_name='baggage_desc',
            name='BAG_MILEAGEPLS_NUM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag_mileage_num', to='File_missing_report.Customer'),
        ),
        migrations.AddField(
            model_name='baggage_content_img',
            name='WAREHOUSE_CONT_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='File_missing_report.Baggage_Desc'),
        ),
    ]
